# -*- coding: utf-8 -*-
"""NLP-ChatBot1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d2_fRUYyWgUeL_1E7DR-XpOQIr4bakVu
"""

!pip install -q datasets transformers evaluate rouge_score sacrebleu accelerate sentence-transformers gradio scikit-learn pandas

from datasets import load_dataset
import numpy as np
import pandas as pd
import re

raw = load_dataset("truehealth/medicationqa")["train"]

def clean_text(x):
    if x is None:
        return ""
    x = str(x).replace("\n", " ").replace("\t", " ")
    x = re.sub(r"\s+", " ", x).strip()
    return x

def normalize_example(ex):
    return {
        "Question": clean_text(ex["Question"]),
        "Focus (Drug)": clean_text(ex["Focus (Drug)"]),
        "Question Type": clean_text(ex["Question Type"]),
        "Section Title": clean_text(ex["Section Title"]),
        "Answer": clean_text(ex["Answer"]),
        "URL": clean_text(ex["URL"]),
    }

data = raw.map(normalize_example)
data = data.filter(lambda x: len(x["Question"]) > 0 and len(x["Answer"]) > 0)

split1 = data.train_test_split(test_size=0.2, seed=42)
train_data = split1["train"]
temp_data = split1["test"]
split2 = temp_data.train_test_split(test_size=0.5, seed=42)
val_data = split2["train"]
test_data = split2["test"]

print(len(train_data), len(val_data), len(test_data))

def make_input(ex):
    return (
        "Answer the medication question using only reliable drug information. "
        "If interaction or safety is asked, mention that the user should ask a doctor/pharmacist.\n"
        f"Question: {ex['Question']}\n"
        f"Drug: {ex['Focus (Drug)']}\n"
        f"Question type: {ex['Question Type']}\n"
        f"Relevant section: {ex['Section Title']}\n"
        "Answer:"
    )

print(make_input(train_data[0]))
print("REFERENCE:", train_data[0]["Answer"][:300])

import torch
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM, DataCollatorForSeq2Seq
from transformers import Seq2SeqTrainingArguments, Seq2SeqTrainer

model_name = "google/flan-t5-base"

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSeq2SeqLM.from_pretrained(model_name)

max_input_length = 256
max_target_length = 128

def safe_text(x):
    if x is None:
        return ""
    return str(x).strip()

def tokenize_function(examples):
    inputs = []
    targets = []

    for i in range(len(examples["Question"])):
        ex = {k: examples[k][i] for k in examples.keys()}

        question = safe_text(ex.get("Question", ""))
        answer = safe_text(ex.get("Answer", ""))

        if question == "" or answer == "":
            continue

        inputs.append(make_input(ex))
        targets.append(answer)

    model_inputs = tokenizer(
        inputs,
        max_length=max_input_length,
        truncation=True,
        padding=False
    )

    labels = tokenizer(
        text_target=targets,
        max_length=max_target_length,
        truncation=True,
        padding=False
    )

    model_inputs["labels"] = labels["input_ids"]

    return model_inputs

tokenized_train = train_data.map(
    tokenize_function,
    batched=True,
    remove_columns=train_data.column_names
)

tokenized_val = val_data.map(
    tokenize_function,
    batched=True,
    remove_columns=val_data.column_names
)

tokenized_test = test_data.map(
    tokenize_function,
    batched=True,
    remove_columns=test_data.column_names
)

data_collator = DataCollatorForSeq2Seq(
    tokenizer=tokenizer,
    model=model,
    label_pad_token_id=-100
)

print("Train size:", len(tokenized_train))
print("Val size:", len(tokenized_val))
print("Test size:", len(tokenized_test))

print("Input:")
print(tokenizer.decode(tokenized_train[0]["input_ids"]))

print("\nLabel:")
print(tokenizer.decode(tokenized_train[0]["labels"]))

from transformers import Seq2SeqTrainingArguments, Seq2SeqTrainer
training_args = Seq2SeqTrainingArguments(
    output_dir="./flan-t5-medicationqa",
    eval_strategy="epoch",
    save_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=2,
    per_device_eval_batch_size=2,
    gradient_accumulation_steps=4,
    num_train_epochs=5,
    weight_decay=0.01,
    predict_with_generate=True,
    generation_max_length=128,
    generation_num_beams=2,
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    save_total_limit=2,
    logging_steps=20,
    report_to="none",
    fp16=False,   # önemli
)

trainer = Seq2SeqTrainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_train,
    eval_dataset=tokenized_val,
    processing_class=tokenizer,
    data_collator=data_collator,
)

trainer.train()
trainer.save_model("./flan-t5-medicationqa-final")
tokenizer.save_pretrained("./flan-t5-medicationqa-final")

def ask_flan_t5(question, drug="", qtype="", section=""):
    ex = {
        "Question": clean_text(question),
        "Focus (Drug)": clean_text(drug),
        "Question Type": clean_text(qtype),
        "Section Title": clean_text(section),
    }
    input_text = make_input(ex)
    inputs = tokenizer(input_text, return_tensors="pt", max_length=max_input_length, truncation=True).to(model.device)

    with torch.no_grad():
        # outputs = model.generate(
        #     **inputs,
        #     max_new_tokens=160,
        #     min_new_tokens=20,
        #     num_beams=4,
        #     no_repeat_ngram_size=4,
        #     repetition_penalty=1.25,
        #     length_penalty=0.8,
        #     early_stopping=True,
        # )
        outputs = model.generate(
              **inputs,
              max_new_tokens=220,
              min_new_tokens=40,
              num_beams=4,
              no_repeat_ngram_size=4,
              repetition_penalty=1.2,
              length_penalty=1.1,
              early_stopping=True,
          )
    return tokenizer.decode(outputs[0], skip_special_tokens=True).strip()

ask_flan_t5(
    "how does rivastigmine and otc sleep medicine interact",
    drug="rivastigmine",
    qtype="Interaction",
    section="What special precautions should I follow?"
)

rouge = evaluate.load("rouge")
bleu = evaluate.load("sacrebleu")

def f1_score(pred, ref):
    pred_tokens = pred.split()
    ref_tokens = ref.split()

    common = Counter(pred_tokens) & Counter(ref_tokens)
    num_same = sum(common.values())

    if num_same == 0:
        return 0

    precision = num_same / len(pred_tokens)
    recall = num_same / len(ref_tokens)

    return 2 * precision * recall / (precision + recall)

def compute_metrics():
    predictions = []
    references = []

    sample_data = test_data.select(range(min(100, len(test_data))))

    for example in sample_data:
        question = example["Question"]
        true_answer = example["Answer"]

        pred = ask_flan_t5(
            question,
            drug=example.get("Focus (Drug)", ""),
            qtype=example.get("Question Type", ""),
            section=example.get("Section Title", "")
        )

        if pred is None or pred.strip() == "":
            pred = " "

        predictions.append(str(pred))
        references.append(str(true_answer))

    rouge_result = rouge.compute(predictions=predictions, references=references)

    bleu_result = bleu.compute(
        predictions=predictions,
        references=[[ref] for ref in references]
    )

    exact_match = np.mean([
        p.strip().lower() == r.strip().lower()
        for p, r in zip(predictions, references)
    ])

    f1 = np.mean([f1_score(p, r) for p, r in zip(predictions, references)])

    return rouge_result, bleu_result, exact_match, f1

rouge_result, bleu_result, exact_match, f1 = compute_metrics()

print("ROUGE:", rouge_result)
print("BLEU:", bleu_result)
print("Exact Match:", exact_match)
print("F1 Score:", f1)

import shutil

shutil.make_archive("flan_t5_model", 'zip', "flan-t5-medicationqa-final")

from google.colab import files
files.download("flan_t5_model.zip")